title: Game Makers Guild
description: >
  Game Makers Guild student organization at the University of Florida. See the
  projects we're currently working on, and learn when and where we meet.
exclude:
  - vendor
